program: resnet_train.py
method: bayes
metric:
  name: val_acc
  goal: maximize
parameters:
  learning_rate:
    min: 0.0001
    max: 0.001
    distribution: log_uniform_values
  epochs:
    value: 100
  model_select:
    values: [18, 50]
  stft_pair:
    values:
      - "512x256"
      - "1024x512"
      - "2048x1024"
  stft_power:
    values: [1.0, 2.0]
