program: vit_train.py
method: bayes
metric:
  name: val_acc
  goal: maximize
parameters:
  learning_rate:
    min: 0.0001
    max: 0.001
    distribution: log_uniform_values
  epochs:
    value: 50
  parameters_grid:
    values:
      - stft_nperseg: 256
        stft_hop: 128
      - stft_nperseg: 512
        stft_hop: 128
      - stft_nperseg: 512
        stft_hop: 256
      - stft_nperseg: 1024
        stft_hop: 256
      - stft_nperseg: 1024
        stft_hop: 512
      - stft_nperseg: 2048
        stft_hop: 512
      - stft_nperseg: 2048
        stft_hop: 1024
  stft_power:
    values: [1.0, 2.0]
